spring:
  application:
    name: hotel
  #spring mongodb
  data:
    mongodb:
      uri: mongodb+srv://alvin930490:ddFCQqJzgaOc3j87@cluster0.qwysd.mongodb.net/hotel_sys?retryWrites=true&w=majority&appName=Cluster0

#swagger
springdoc:
  api-docs:
    path: /api-docs  # OpenAPI JSON 
  swagger-ui:
    path: /swagger-ui.html  # Swagger UI ????
    enabled: true           # ?????

kaolee:
  jwt:
    # 設置jwt簽章加密時使用的密鑰
    user-secret-key: a-very-long-and-secure-secret-key-kaolee
    # 配置jwt過期时间
    user-ttl: 7200000
    # 配置前端傳遞過來的令牌名稱
    user-token-name: token





